In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/test_data.csv') #считываю данные

In [ ]:
df.info() #смотрю на тип данных

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Campaign_id        87 non-null     int64
 1   Geo                87 non-null     object
 2   Buyer              87 non-null     object
 3   Impressions        87 non-null     int64
 4   Clicks             87 non-null     int64
 5   Installs           87 non-null     int64
 6   Registrations      87 non-null     int64
 7   Spend              87 non-null     object
 8   Revenue_ad1d       87 non-null     object
 9   Revenue_in_app1d   87 non-null     object
 10  Payers1d           87 non-null     int64
 11  Revenue_ad7d       87 non-null     object
 12  Revenue_in_app7d   87 non-null     object
 13  Payers7d           87 non-null     int64
 14  Revenue_ad30d      87 non-null     object
 15  Revenue_in_app30d  87 non-null     object
 16  Payers30d          87 non-null     int64
dtypes: int64(8), object(9)
memory usage: 11.7+ KB

In [ ]:
df.head() #просто смотрю на датафрейм

,Campaign_id,Geo,Buyer,Impressions,Clicks,Installs,Registrations,Spend,Revenue_ad1d,Revenue_in_app1d,Payers1d,Revenue_ad7d,Revenue_in_app7d,Payers7d,Revenue_ad30d,Revenue_in_app30d,Payers30d
0,1,north america,buyer_1,3456974,129508,33054,21932,"3208,440002","1163,521408","162,220001",64,"1381,310062","199,749999",79,"1527,013835","276,629998",83
1,2,north america,buyer_2,245542,6306,3401,2448,"1569,519999","833,059639","37,25",17,"1200,964697","69,340001",19,"1449,001828","120,250001",22
2,3,north america,buyer_1,1281103,35724,13315,8101,"1231,999998","459,6826","3,26",4,"524,987826","24,7",6,"572,633765","24,7",6
3,4,north america,buyer_1,215538,9987,3119,1857,"1228,129999","602,77816","26,13",11,"830,113889","33,439999",12,"1042,831595","57,530002",12
4,5,western europe,buyer_2,335878,7343,3952,2955,"872,570005","427,807238","19,030001",4,"577,039081","20,640001",5,"714,554179","32,150001",6

предобработка данных

In [ ]:
df['Spend'] = df['Spend'].str.replace(",", ".") #заменяю запятую на точку
df['Spend'] = df['Spend'].astype(float).round(2) #преобразовывую в подходящий тип данных

df['Revenue_ad1d'] = df['Revenue_ad1d'].str.replace(",", ".")
df['Revenue_ad1d'] = df['Revenue_ad1d'].astype(float).round(2)

df['Revenue_in_app1d'] = df['Revenue_in_app1d'].str.replace(",", ".")
df['Revenue_in_app1d'] = df['Revenue_in_app1d'].astype(float).round(2)

df['Revenue_ad7d'] = df['Revenue_ad7d'].str.replace(",", ".")
df['Revenue_ad7d'] = df['Revenue_ad7d'].astype(float).round(2)

df['Revenue_in_app7d'] = df['Revenue_in_app7d'].str.replace(",", ".")
df['Revenue_in_app7d'] = df['Revenue_in_app7d'].astype(float).round(2)

df['Revenue_ad30d'] = df['Revenue_ad30d'].str.replace(",", ".")
df['Revenue_ad30d'] = df['Revenue_ad30d'].astype(float).round(2)

df['Revenue_in_app30d'] = df['Revenue_in_app30d'].str.replace(",", ".")
df['Revenue_in_app30d'] = df['Revenue_in_app30d'].astype(float).round(2)

In [ ]:
df.head()

,Campaign_id,Geo,Buyer,Impressions,Clicks,Installs,Registrations,Spend,Revenue_ad1d,Revenue_in_app1d,Payers1d,Revenue_ad7d,Revenue_in_app7d,Payers7d,Revenue_ad30d,Revenue_in_app30d,Payers30d
0,1,north america,buyer_1,3456974,129508,33054,21932,3208.44,1163.52,162.22,64,1381.31,199.75,79,1527.01,276.63,83
1,2,north america,buyer_2,245542,6306,3401,2448,1569.52,833.06,37.25,17,1200.96,69.34,19,1449.00,120.25,22
2,3,north america,buyer_1,1281103,35724,13315,8101,1232.00,459.68,3.26,4,524.99,24.70,6,572.63,24.70,6
3,4,north america,buyer_1,215538,9987,3119,1857,1228.13,602.78,26.13,11,830.11,33.44,12,1042.83,57.53,12
4,5,western europe,buyer_2,335878,7343,3952,2955,872.57,427.81,19.03,4,577.04,20.64,5,714.55,32.15,6

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Campaign_id        87 non-null     int64
 1   Geo                87 non-null     object
 2   Buyer              87 non-null     object
 3   Impressions        87 non-null     int64
 4   Clicks             87 non-null     int64
 5   Installs           87 non-null     int64
 6   Registrations      87 non-null     int64
 7   Spend              87 non-null     float64
 8   Revenue_ad1d       87 non-null     float64
 9   Revenue_in_app1d   87 non-null     float64
 10  Payers1d           87 non-null     int64
 11  Revenue_ad7d       87 non-null     float64
 12  Revenue_in_app7d   87 non-null     float64
 13  Payers7d           87 non-null     int64
 14  Revenue_ad30d      87 non-null     float64
 15  Revenue_in_app30d  87 non-null     float64
 16  Payers30d          87 non-null     int64
dtypes: float64(7), int64(8), object(2)
memory usage: 11.7+ KB

In [ ]:
df.describe()

,Campaign_id,Impressions,Clicks,Installs,Registrations,Spend,Revenue_ad1d,Revenue_in_app1d,Payers1d,Revenue_ad7d,Revenue_in_app7d,Payers7d,Revenue_ad30d,Revenue_in_app30d,Payers30d
count,87.000000,8.700000e+01,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000,87.000000
mean,44.000000,1.140572e+05,3804.494253,1211.850575,769.057471,208.878506,87.254483,5.661724,2.034483,118.064598,7.762644,2.551724,145.331954,11.093563,2.816092
std,25.258662,3.989255e+05,14610.898115,3883.087208,2577.564690,424.243533,177.725244,18.486891,7.169782,231.951235,23.609511,8.798465,278.148699,33.554932,9.299323
min,1.000000,2.185000e+03,53.000000,10.000000,2.000000,20.410000,0.370000,0.000000,0.000000,0.370000,0.000000,0.000000,0.370000,0.000000,0.000000
25%,22.500000,1.057700e+04,276.500000,107.500000,44.500000,27.680000,8.955000,0.000000,0.000000,11.860000,0.000000,0.000000,12.755000,0.000000,0.000000
50%,44.000000,2.619300e+04,724.000000,258.000000,147.000000,73.160000,19.180000,0.000000,0.000000,23.720000,0.000000,0.000000,30.780000,0.550000,1.000000
75%,65.500000,7.088950e+04,2063.500000,763.500000,501.500000,191.175000,91.550000,3.830000,2.000000,123.990000,6.015000,2.000000,145.035000,8.600000,3.000000
max,87.000000,3.456974e+06,129508.000000,33054.000000,21932.000000,3208.440000,1163.520000,162.220000,64.000000,1381.310000,199.750000,79.000000,1527.010000,276.630000,83.000000

## **Кампании в каких гео показали себя хуже всего?**

посчитаем конверсию в каждом регионе и найдем слабый

In [ ]:
df_geo = df.groupby('Geo', as_index=False).agg({'Impressions':'sum','Registrations':'sum'})

In [ ]:
df_geo['con'] = df_geo['Registrations']/df_geo['Impressions']*100

In [ ]:
df_geo.sort_values('con', ascending = True)

                 Geo  Impressions  Registrations       con
0  australia oceania         2185              9  0.411899
5    tropical africa        90894            485  0.533589
1                cis       729586           4069  0.557714
2      latin america       522450           3507  0.671260
6     western europe       827297           5594  0.676178
4      north america      6801913          46175  0.678853
3       north africa       948653           7069  0.745162

по конверсии от показа за регистрации можно увидеть, что australia oceania показал себя хуже всех.

# **Кто из медиабайеров лучше всего окупается?**

In [ ]:
df.head(1)

,Campaign_id,Geo,Buyer,Impressions,Clicks,Installs,Registrations,Spend,Revenue_ad1d,Revenue_in_app1d,Payers1d,Revenue_ad7d,Revenue_in_app7d,Payers7d,Revenue_ad30d,Revenue_in_app30d,Payers30d
0,1,north america,buyer_1,3456974,129508,33054,21932,3208.44,1163.52,162.22,64,1381.31,199.75,79,1527.01,276.63,83

In [ ]:
df_buyers = df.groupby('Buyer', as_index=False).agg({'Spend':'sum','Revenue_ad30d':'sum'})

In [ ]:
df_buyers['profit'] = df_buyers['Revenue_ad30d']-df_buyers['Spend']

In [ ]:
df_buyers[df_buyers['profit']>0]

     Buyer    Spend  Revenue_ad30d  profit
2  buyer_3  1953.72        2046.72    93.0

**Ответ: buyer_3 окупился на 93 единицы**

# **У каких кампаний дешевле установки (CPI)**

In [ ]:
df_cpi = df.groupby('Campaign_id',as_index=False).agg({'Spend':'sum','Installs':'sum'})

In [ ]:
df_cpi.head()

   Campaign_id    Spend  Installs
0            1  3208.44     33054
1            2  1569.52      3401
2            3  1232.00     13315
3            4  1228.13      3119
4            5   872.57      3952

In [ ]:
df_cpi['cpi'] = df_cpi['Spend']/df_cpi['Installs']

**список кампаний у которых CPI дешевле**

In [ ]:
df_cpi.sort_values('cpi').head(5)

    Campaign_id   Spend  Installs       cpi
20           21  204.39      8069  0.025330
55           56   43.50      1591  0.027341
44           45   69.08      1969  0.035084
26           27  143.82      3133  0.045905
40           41   82.39      1610  0.051174

# **Воронки**

In [ ]:
df.head()

,Campaign_id,Geo,Buyer,Impressions,Clicks,Installs,Registrations,Spend,Revenue_ad1d,Revenue_in_app1d,Payers1d,Revenue_ad7d,Revenue_in_app7d,Payers7d,Revenue_ad30d,Revenue_in_app30d,Payers30d
0,1,north america,buyer_1,3456974,129508,33054,21932,3208.44,1163.52,162.22,64,1381.31,199.75,79,1527.01,276.63,83
1,2,north america,buyer_2,245542,6306,3401,2448,1569.52,833.06,37.25,17,1200.96,69.34,19,1449.00,120.25,22
2,3,north america,buyer_1,1281103,35724,13315,8101,1232.00,459.68,3.26,4,524.99,24.70,6,572.63,24.70,6
3,4,north america,buyer_1,215538,9987,3119,1857,1228.13,602.78,26.13,11,830.11,33.44,12,1042.83,57.53,12
4,5,western europe,buyer_2,335878,7343,3952,2955,872.57,427.81,19.03,4,577.04,20.64,5,714.55,32.15,6

In [ ]:
df_buyer_funnel = df.groupby('Buyer',as_index=False).agg({'Impressions':'sum','Clicks':'sum','Installs':'sum','Registrations':'sum'})

In [ ]:
df_buyer_funnel

     Buyer  Impressions  Clicks  Installs  Registrations
0  buyer_1      6239438  226710     63265          40161
1  buyer_2      1929911   50205     24654          14882
2  buyer_3       336414   11266      3801           2569
3  buyer_4       312096    7129      2661           1708
4  buyer_5      1105119   35681     11050           7588

In [ ]:
df_buyer_funnel.columns[1:]

Index(['Impressions', 'Clicks', 'Installs', 'Registrations'], dtype='object')

In [ ]:
df_buyer_funnel.iloc[0,1:]

Buyer            buyer_1
Impressions      6239438
Clicks            226710
Installs           63265
Registrations      40161
Name: 0, dtype: object

In [ ]:
from plotly import graph_objects as go

fig = go.Figure(go.Funnel(
    y = df_buyer_funnel.columns[1:],
    x = df_buyer_funnel.iloc[0,1:],
    textinfo = "value+percent initial"
    ))

fig.update_layout(
    title={
        'text': "Воронка buyer_1",
        'y': 0.88,
        'x': 0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font_size': 24
    })

fig.show()

In [ ]:
from plotly import graph_objects as go

fig = go.Figure(go.Funnel(
    y = df_buyer_funnel.columns[1:],
    x = df_buyer_funnel.iloc[1,1:],
    textinfo = "value+percent initial"
    ))

fig.update_layout(
    title={
        'text': "Воронка buyer_2",
        'y': 0.88,
        'x': 0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font_size': 24
    })

fig.show()

In [ ]:
from plotly import graph_objects as go

fig = go.Figure(go.Funnel(
    y = df_buyer_funnel.columns[1:],
    x = df_buyer_funnel.iloc[2,1:],
    textinfo = "value+percent initial"
    ))

fig.update_layout(
    title={
        'text': "Воронка buyer_3",
        'y': 0.88,
        'x': 0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font_size': 24
    })

fig.show()

In [ ]:
from plotly import graph_objects as go

fig = go.Figure(go.Funnel(
    y = df_buyer_funnel.columns[1:],
    x = df_buyer_funnel.iloc[3,1:],
    textinfo = "value+percent initial"
    ))

fig.update_layout(
    title={
        'text': "Воронка buyer_4",
        'y': 0.88,
        'x': 0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font_size': 24
    })

fig.show()

In [ ]:
from plotly import graph_objects as go

fig = go.Figure(go.Funnel(
    y = df_buyer_funnel.columns[1:],
    x = df_buyer_funnel.iloc[4,1:],
    textinfo = "value+percent initial"
    ))

fig.update_layout(
    title={
        'text': "Воронка buyer_5",
        'y': 0.88,
        'x': 0.5,
        'xanchor': 'center',
        'yanchor': 'top',
        'font_size': 24
    })

fig.show()

# **Click-through rate для каждого байера**

In [ ]:
df.head()

,Campaign_id,Geo,Buyer,Impressions,Clicks,Installs,Registrations,Spend,Revenue_ad1d,Revenue_in_app1d,Payers1d,Revenue_ad7d,Revenue_in_app7d,Payers7d,Revenue_ad30d,Revenue_in_app30d,Payers30d
0,1,north america,buyer_1,3456974,129508,33054,21932,3208.44,1163.52,162.22,64,1381.31,199.75,79,1527.01,276.63,83
1,2,north america,buyer_2,245542,6306,3401,2448,1569.52,833.06,37.25,17,1200.96,69.34,19,1449.00,120.25,22
2,3,north america,buyer_1,1281103,35724,13315,8101,1232.00,459.68,3.26,4,524.99,24.70,6,572.63,24.70,6
3,4,north america,buyer_1,215538,9987,3119,1857,1228.13,602.78,26.13,11,830.11,33.44,12,1042.83,57.53,12
4,5,western europe,buyer_2,335878,7343,3952,2955,872.57,427.81,19.03,4,577.04,20.64,5,714.55,32.15,6

In [ ]:
df_ctr = df.groupby('Buyer', as_index=False).agg({'Clicks':'sum','Impressions':'sum'})

In [ ]:
df_ctr['ctr'] = df_ctr['Clicks']/df_ctr['Impressions']*100

In [ ]:
df_ctr[['Buyer','ctr']]

     Buyer       ctr
0  buyer_1  3.633500
1  buyer_2  2.601415
2  buyer_3  3.348850
3  buyer_4  2.284233
4  buyer_5  3.228702

# **Cost per registration для каждого байера**

In [ ]:
df_cpr = df.groupby('Buyer', as_index=False).agg({'Spend':'sum','Registrations':'sum'})

In [ ]:
df_cpr['cpr'] = df_cpr['Spend']/df_cpr['Registrations']

In [ ]:
df_cpr[['Buyer','cpr']]

     Buyer       cpr
0  buyer_1  0.179556
1  buyer_2  0.485516
2  buyer_3  0.760498
3  buyer_4  0.668074
4  buyer_5  0.084481

# **ARPPU (average revenue per paying user) для каждого байера на 3 этапах 1,7,30 день с покупок в приложении**

In [ ]:
df.head()

,Campaign_id,Geo,Buyer,Impressions,Clicks,Installs,Registrations,Spend,Revenue_ad1d,Revenue_in_app1d,Payers1d,Revenue_ad7d,Revenue_in_app7d,Payers7d,Revenue_ad30d,Revenue_in_app30d,Payers30d
0,1,north america,buyer_1,3456974,129508,33054,21932,3208.44,1163.52,162.22,64,1381.31,199.75,79,1527.01,276.63,83
1,2,north america,buyer_2,245542,6306,3401,2448,1569.52,833.06,37.25,17,1200.96,69.34,19,1449.00,120.25,22
2,3,north america,buyer_1,1281103,35724,13315,8101,1232.00,459.68,3.26,4,524.99,24.70,6,572.63,24.70,6
3,4,north america,buyer_1,215538,9987,3119,1857,1228.13,602.78,26.13,11,830.11,33.44,12,1042.83,57.53,12
4,5,western europe,buyer_2,335878,7343,3952,2955,872.57,427.81,19.03,4,577.04,20.64,5,714.55,32.15,6

**на первый день**

In [ ]:
df_arppu1 = df.groupby('Buyer', as_index=False).agg({'Revenue_in_app1d':'sum','Payers1d':'sum'})

In [ ]:
df_arppu1['arppu'] = df_arppu1['Revenue_in_app1d']/df_arppu1['Payers1d']

In [ ]:
df_arppu1[['Buyer','arppu']]

     Buyer     arppu
0  buyer_1  2.332784
1  buyer_2  2.891600
2  buyer_3  4.538125
3  buyer_4  3.538462
4  buyer_5  3.100000

**на седьмой день**

In [ ]:
df_arppu7 = df.groupby('Buyer', as_index=False).agg({'Revenue_in_app7d':'sum','Payers7d':'sum'})

In [ ]:
df_arppu7['arppu'] = df_arppu7['Revenue_in_app7d']/df_arppu7['Payers7d']

In [ ]:
df_arppu7[['Buyer','arppu']]

     Buyer     arppu
0  buyer_1  2.507627
1  buyer_2  3.310435
2  buyer_3  4.788095
3  buyer_4  3.644615
4  buyer_5  3.100000

**на тридцатый день**

In [ ]:
df_arppu30 = df.groupby('Buyer', as_index=False).agg({'Revenue_in_app30d':'sum','Payers30d':'sum'})

In [ ]:
df_arppu30['arppu'] = df_arppu30['Revenue_in_app30d']/df_arppu30['Payers30d']

In [ ]:
df_arppu30[['Buyer','arppu']]

     Buyer     arppu
0  buyer_1  3.336532
1  buyer_2  4.556203
2  buyer_3  4.298077
3  buyer_4  5.423571
4  buyer_5  1.895000

# **Cost per click**

In [ ]:
df_cpc = df.groupby('Buyer', as_index=False).agg({'Spend':'sum','Clicks':'sum'})

In [ ]:
df_cpc['cpc'] = df_cpr['Spend']/df_cpr['Clicks']

In [ ]:
df_cpc[['Buyer','cpc']]

     Buyer       cpc
0  buyer_1  0.031808
1  buyer_2  0.143919
2  buyer_3  0.173417
3  buyer_4  0.160060
4  buyer_5  0.017966

# **ARPU**

Если это регистрации за 30 дней то можно посчитать ARPU

In [ ]:
df_arpu = df.groupby('Buyer', as_index=False).agg({'Revenue_in_app30d':'sum','Revenue_ad30d':'sum','Registrations':'sum'})

In [ ]:
df_arpu['arpu'] = (df_arpu['Revenue_in_app30d']+df_arpu['Revenue_ad30d'])/df_arpu['Registrations']

In [ ]:
df_arpu[['Buyer','arpu']]

     Buyer      arpu
0  buyer_1  0.106787
1  buyer_2  0.402121
2  buyer_3  0.840199
3  buyer_4  0.563554
4  buyer_5  0.028326